#!/usr/bin/bash

# create a sample cinema database in the current directory
mkdir cinema_databases
pushd cinema_databases > /dev/null 2>&1
mkdir pantheon.cdb 
pushd pantheon.cdb > /dev/null 2>&1

touch data.csv
mkdir 0
mkdir 1
mkdir 2
touch 0/000.png
touch 1/000.png
touch 2/000.png

popd > /dev/null 2>&1
popd > /dev/null 2>&1
popd > /dev/null 2>&1
